version: "{build}"

clone_depth: 1

environment:
  matrix:
    - nodejs_version: 6

platform:
  - x86
  - x64

build: off

test_script:
  - echo %platform%
  - echo %PLATFORM%

matrix:
  fast_finish: true
